### ISSUE TITLE
Support Vite 4

### ISSUE THREAD

**Issue by mattpilott** [macropygia/static-site-stack#5]
Currently theres a missing peer dependency warning when using this with vite 4

https://github.com/macropygia/static-site-stack/tree/main/packages/vite-plugin-glob-input

**Comment by macropygia** [comment]
Under testing. Please wait while I do this.

**Comment by mattpilott** [comment]
I'm happy to test the new version if you wanted to release a beta

**Comment by macropygia** [comment]
Vite 4 has been added to `peerDependencies` in all active vite plugins. Already released.
AFAIK, the breaking changes in Rollup 3 did not affect except `vite-plugin-imagemin-cache` .

**Comment by mattpilott** [comment]
Works great, thank you!
